### ISSUE TITLE
Create functioning Vue-CLI plugin

### ISSUE THREAD

**Issue by TheJaredWilcurt** [tjw-lint/vue-cli-plugin-jest-serializer-vue-tjw#1]
Ideally it will work like so:

**v1:**

* [x] Add `jest-serializer-vue-tjw` as a `devDependency`
* [x] Detect if the user's Jest config is inside the `package.json` or external
* [x] Add `jest-serializer-vue-tjw` to the Jest config
* [x] Remove `jest-serializer-vue` if it is a `devDependency`
* [x] Remove `jest-serializer-vue` from Jest config

**v2:**

* [x] Add in options to CLI during install to adjust optional settings
* [ ] Add in options to UI to adjust optional settings
* [x] Create one example snapshot test

**Comment by gwenf** [comment]
I'm working on this :)

**Comment by gwenf** [comment]
Should I prompt users for all of these options? Or just some of them?
```js
module.exports = {
  pluginOptions: {
    jestSerializer: {
      attributesToClear: [],
      // All available formatting options: https://github.com/beautify-web/js-beautify/blob/master/js/src/html/options.js
      formatting: {
        indent_char: ' ',
        indent_inner_html: true,
        indent_size: 2,
        inline: [],
        sep: '\n',
        unformatted: ['code', 'pre']
      },
      removeClassTest: false,
      removeComments: false,
      removeDataTest: true,
      removeDataTestid: true,
      removeDataTestId: true,
      removeDataQa: false,
      removeDataVId: true,
      removeIdTest: false,
      removeServerRendered: true,
      addInputValues: false,
      stringifyObjects: false,
      verbose: true
    }
  }
};
```

**Comment by TheJaredWilcurt** [comment]
In the CLI version, it would be nice to have something like

* Use defaults (STRONGLY recommended)
* Advanced settings

Then if they pick advanced, show them:

```
Show helpful error messages? Y/n

Remove the following from your snapshots:
* data-test Attributes? Y/n
* data-testid Attributes? Y/n
* data-test-id Attributes? Y/n
* data-qa Attributes? y/N
* data-v-ID's from scoped styles? Y/n
* Server Rendered attributes? Y/n
* Classes that start with test? y/N
* ID attributes that start with test? y/N
* HTML Comments? y/N

Experimental snapshot features (not recommended):
* Add Input Values? y/N
* Stringify Objects? y/N

Attributes to clear and formatting options can be edited in the jest.config.js file manually.
```

From the Vue-CLI UI, it would be nice to have all options there, including text inputs for the `attributesToClear` and the `formatting` object.

**Comment by gwenf** [comment]
Ok, almost done. 
<img width="1440" alt="Screen Shot 2020-06-15 at 11 14 01 PM" src="https://user-images.githubusercontent.com/10039233/84727946-2a519e00-af5e-11ea-8c01-01c87f4c348f.png">
<img width="1440" alt="Screen Shot 2020-06-15 at 11 14 15 PM" src="https://user-images.githubusercontent.com/10039233/84727947-2aea3480-af5e-11ea-96ae-b761ec1d41f2.png">

**Comment by TheJaredWilcurt** [comment]
`Select the options that you want removed from your snapshots` is confusingly worded. Also it doesn't give you the defaults to opt-in or out of. Everything is disabled by default there.

The `y/N` or `Y/n` is intentional.

**Comment by gwenf** [comment]
Ok, I thought it would be easier to put them in a list. I will fix it.

**Comment by gwenf** [comment]
<img width="1435" alt="Screen Shot 2020-06-19 at 7 26 28 PM" src="https://user-images.githubusercontent.com/10039233/85185639-d77c2d00-b262-11ea-89ec-525a902c718e.png">

**Comment by TheJaredWilcurt** [comment]
If you can have items in the list enabled by default, then the list is better. otherwise, I guess this is okay

**Comment by gwenf** [comment]
Ok, I can go back to the list with defaults selected.
